// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXWD4A-LURys5LFGnzNEowKiR5VG8byds',
    appId: '1:581690002106:web:948e89f83ab3dc0efad083',
    messagingSenderId: '581690002106',
    projectId: 'flutter-tutorial-2dc10',
    authDomain: 'flutter-tutorial-2dc10.firebaseapp.com',
    storageBucket: 'flutter-tutorial-2dc10.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt4PGMG_QZK-Ojsd1qGe9UsQf86VKpG58',
    appId: '1:581690002106:android:a04b0c391afd633ffad083',
    messagingSenderId: '581690002106',
    projectId: 'flutter-tutorial-2dc10',
    storageBucket: 'flutter-tutorial-2dc10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAVSAc42ZgfMyHhz6fOpqzMbmIcZFXyOY',
    appId: '1:581690002106:ios:84166a0f6f9814fdfad083',
    messagingSenderId: '581690002106',
    projectId: 'flutter-tutorial-2dc10',
    storageBucket: 'flutter-tutorial-2dc10.firebasestorage.app',
    iosBundleId: 'com.example.navigation2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAVSAc42ZgfMyHhz6fOpqzMbmIcZFXyOY',
    appId: '1:581690002106:ios:84166a0f6f9814fdfad083',
    messagingSenderId: '581690002106',
    projectId: 'flutter-tutorial-2dc10',
    storageBucket: 'flutter-tutorial-2dc10.firebasestorage.app',
    iosBundleId: 'com.example.navigation2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXWD4A-LURys5LFGnzNEowKiR5VG8byds',
    appId: '1:581690002106:web:c9ad9d89cf7d8201fad083',
    messagingSenderId: '581690002106',
    projectId: 'flutter-tutorial-2dc10',
    authDomain: 'flutter-tutorial-2dc10.firebaseapp.com',
    storageBucket: 'flutter-tutorial-2dc10.firebasestorage.app',
  );
}
